name: Erlang CI

on:
  push:
    branches: [ .app ]
  pull_request:
    branches: [ git@container.im:$termux-io/rakudocker.git ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, ct
